### ISSUE TITLE
我这边 . 开启后3.5mm 输入被干扰了

### ISSUE THREAD

**Issue by enefry** [tankririri/RaspberryPi_CPU_PWM#1]
我这边 . 开启后3.5mm 输入被干扰了,一直听到滋滋滋.将 pwm 设置为0,风扇停止后声音播放就出来了.
电路和你这个博客 http://www.zhangminghao.com/post/43.html 一样

**Comment by zhangminghao1989** [comment]
这是电磁干扰，你需要想办法进行电磁屏蔽。
你先测试一下是什么引起的电磁干扰，风扇、三极管、PWM？

**Comment by enefry** [comment]
不是电磁干扰.是完全没输出.只有滋滋滋的声音. 如果只是干扰就只是音质下降
我看你代码好像没有指定输出针脚.应该是这个原因.
用这段 python 的话是可以的.

	GPIO.setmode(GPIO.BCM)
	GPIO.setup(pin, GPIO.OUT)
	pwm = GPIO.PWM(pin, 100)
	pwm.start(5)
	pwm.ChangeDutyCycle(value)

**Comment by zhangminghao1989** [comment]
gpio mode 1 pwm
这条命令是设置针脚
